import p1 from './assets/shop/1 (1).jpg'
import p2 from './assets/shop/1.jpg'
import p3 from './assets/shop/2 (1).jpg'
import p4 from './assets/shop/2.jpg'
import p5 from './assets/shop/3 (1).jpg'
import p6 from './assets/shop/3 (2).jpg'
import p7 from './assets/shop/4 (1).jpg'
import p8 from './assets/shop/4.jpg'
import p9 from './assets/shop/4.jpg'
import p10 from './assets/shop/6.jpg'
import p11 from './assets/shop/7.jpg'
import p12 from './assets/shop/8.jpg'
import rev from './assets/rev1.jpg'
import rep from './assets/rep.jpg'
const des = 'Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur.'
const com = 'Vestibulum ante ipsum primis aucibus orci luctustrices posuere cubilia Curae Suspendisse viverra ed viverra. Mauris ullarper euismod vehicula. Phasellus quam nisi, congue id nulla.'
export const ShopProductData = [
  {
    id: 1,
    title: "Lorem ipsum accessories one",
    stock: 5,
    img: p1,
    price: 5,
    oldPrice: 4,
    ratings: 5,
    desc: des,
    categories: "accessories",
    tags: "accessories",
    addInfo: {
      weight: "400g",
      dimensions: "10 x 10 x 15 cm",
      materials: "60% cotton, 40% polester",
      otherInfo: " American heirloom jean shorts pug seitan letterpress",
    },
    Reviews: [
      { name: "White Lewis", rating: 5, img: rev, comment: com },
      { name: "White Lewis", rating: 5, img: rep, comment: com },
    ],
  },
  {
    id: 2,
    title: "Lorem ipsum accessories one",
    stock: 5,
    img: p2,
    price: 5,
    status: "Hot",
    oldPrice: 4,
    ratings: 4,
    desc: des,
    categories: "accessories",
    tags: "accessories",
    addInfo: {
      weight: "400g",
      dimensions: "10 x 10 x 15 cm",
      materials: "60% cotton, 40% polester",
      otherInfo: " American heirloom jean shorts pug seitan letterpress",
    },
    Reviews: [
      { name: "White Lewis", rating: 5, img: rev, comment: com },
      { name: "White Lewis", rating: 5, img: rep, comment: com },
    ],
  },
  {
    id: 3,
    title: "Lorem ipsum accessories one",
    img: p3,
    stock: 5,
    price: 3,
    oldPrice: 4,
    status: "New",
    ratings: 4,
    desc: des,
    categories: "accessories",
    tags: "accessories",
    addInfo: {
      weight: "400g",
      dimensions: "10 x 10 x 15 cm",
      materials: "60% cotton, 40% polester",
      otherInfo: " American heirloom jean shorts pug seitan letterpress",
    },
    Reviews: [
      { name: "White Lewis", rating: 5, img: rev, comment: com },
      { name: "White Lewis", rating: 5, img: rep, comment: com },
    ],
  },
  {
    id: 4,
    title: "Lorem ipsum accessories one",
    img: p4,
    stock: 5,
    price: 5,
    status: "New",
    oldPrice: 4,
    ratings: 4.5,
    desc: des,
    categories: "accessories",
    tags: "accessories",
    addInfo: {
      weight: "400g",
      dimensions: "10 x 10 x 15 cm",
      materials: "60% cotton, 40% polester",
      otherInfo: " American heirloom jean shorts pug seitan letterpress",
    },
    Reviews: [
      { name: "White Lewis", rating: 5, img: rev, comment: com },
      { name: "White Lewis", rating: 5, img: rep, comment: com },
    ],
  },
  {
    id: 5,
    title: "Lorem ipsum accessories one",
    img: p5,
    stock: 5,
    price: 5,
    oldPrice: 4,
    ratings: 3.5,
    status: "Hot",
    desc: des,
    categories: "accessories",
    tags: "accessories",
    addInfo: {
      weight: "400g",
      dimensions: "10 x 10 x 15 cm",
      materials: "60% cotton, 40% polester",
      otherInfo: " American heirloom jean shorts pug seitan letterpress",
    },
    Reviews: [
      { name: "White Lewis", rating: 5, img: rev, comment: com },
      { name: "White Lewis", rating: 5, img: rep, comment: com },
    ],
  },
  {
    id: 6,
    title: "Lorem ipsum accessories one",
    img: p6,
    price: 5,
    stock: 5,
    oldPrice: 4,
    status: "New",
    ratings: 5,
    desc: des,
    categories: "accessories",
    tags: "accessories",
    addInfo: {
      weight: "400g",
      dimensions: "10 x 10 x 15 cm",
      materials: "60% cotton, 40% polester",
      otherInfo: " American heirloom jean shorts pug seitan letterpress",
    },
    Reviews: [
      { name: "White Lewis", rating: 5, img: rev, comment: com },
      { name: "White Lewis", rating: 5, img: rep, comment: com },
    ],
  },
  {
    id: 7,
    title: "Lorem ipsum accessories one",
    img: p7,
    price: 44,
    ratings: 3,
    stock: 5,
    desc: des,
    status: "New",
    categories: "accessories",
    tags: "accessories",
    addInfo: {
      weight: "400g",
      dimensions: "10 x 10 x 15 cm",
      materials: "60% cotton, 40% polester",
      otherInfo: " American heirloom jean shorts pug seitan letterpress",
    },
    Reviews: [
      { name: "White Lewis", rating: 5, img: rev, comment: com },
      { name: "White Lewis", rating: 5, img: rep, comment: com },
    ],
  },
  {
    id: 8,
    title: "Lorem ipsum accessories one",
    img: p8,
    price: 5,
    stock: 5,
    oldPrice: 20,
    status: "Hot",
    ratings: 25,
    desc: des,
    categories: "accessories",
    tags: "accessories",
    addInfo: {
      weight: "400g",
      dimensions: "10 x 10 x 15 cm",
      materials: "60% cotton, 40% polester",
      otherInfo: " American heirloom jean shorts pug seitan letterpress",
    },
    Reviews: [
      { name: "White Lewis", rating: 5, img: rev, comment: com },
      { name: "White Lewis", rating: 5, img: rep, comment: com },
    ],
  },
  {
    id: 9,
    title: "Lorem ipsum accessories one",
    img: p9,
    price: 5,
    ratings: 3.5,
    status: "New",
    stock: 5,
    desc: des,
    categories: "accessories",
    tags: "accessories",
    addInfo: {
      weight: "400g",
      dimensions: "10 x 10 x 15 cm",
      materials: "60% cotton, 40% polester",
      otherInfo: " American heirloom jean shorts pug seitan letterpress",
    },
    Reviews: [
      { name: "White Lewis", rating: 5, img: rev, comment: com },
      { name: "White Lewis", rating: 5, img: rep, comment: com },
    ],
  },
  {
    id: 10,
    title: "Lorem ipsum accessories one",
    img: p10,
    price: 20,
    status: "New",
    ratings: 5,
    stock: 5,
    desc: des,
    categories: "accessories",
    tags: "accessories",
    addInfo: {
      weight: "400g",
      dimensions: "10 x 10 x 15 cm",
      materials: "60% cotton, 40% polester",
      otherInfo: " American heirloom jean shorts pug seitan letterpress",
    },
    Reviews: [
      { name: "White Lewis", rating: 5, img: rev, comment: com },
      { name: "White Lewis", rating: 5, img: rep, comment: com },
    ],
  },
  {
    id: 11,
    title: "Lorem ipsum accessories one",
    img: p11,
    price: 10,
    oldPrice: 5,
    ratings: 5,
    stock: 5,
    status: "New",
    desc: des,
    categories: "accessories",
    tags: "accessories",
    addInfo: {
      weight: "400g",
      dimensions: "10 x 10 x 15 cm",
      materials: "60% cotton, 40% polester",
      otherInfo: " American heirloom jean shorts pug seitan letterpress",
    },
    Reviews: [
      { name: "White Lewis", rating: 5, img: rev, comment: com },
      { name: "White Lewis", rating: 5, img: rep, comment: com },
    ],
  },
  {
    id: 12,
    title: "Lorem ipsum accessories one",
    img: p12,
    price: 10,
    oldPrice: 5,
    ratings: 5,
    stock: 5,
    status: "New",
    desc: des,
    categories: "accessories",
    tags: "accessories",
    addInfo: {
      weight: "400g",
      dimensions: "10 x 10 x 15 cm",
      materials: "60% cotton, 40% polester",
      otherInfo: " American heirloom jean shorts pug seitan letterpress",
    },
    Reviews: [
      { name: "White Lewis", rating: 5, img: rev, comment: com },
      { name: "White Lewis", rating: 5, img: rep, comment: com },
    ],
  },
];